### ISSUE TITLE
Problem: error creating encrypted location in aip-encrypt-mirror

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/archivematica-acceptance-tests#105]
Full report here: https://gist.github.com/sevein/5089b424e1faa20717fb9dc26ddf8e73.

This is unexpected:

    selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: form[action="/spaces/Create/location_create/"]

The error reads `/spaces/Create/location_create/` but instead of `Create` I would expect a UUID.

This is how I am invoking behave:

```
env \
    HEADLESS=0 \
        behave \
            --tags=mo-aip-reingest,ipc,icc,tpc,picc,premis-events,aip-encrypt-mirror,aip-encrypt \
            --stop --no-skipped -v -D driver_name=Firefox \
            -D ssh_accessible=yes \
            -D ssh_requires_password=no \
            -D ssh_identity_file=keys/id_rsa \
            -D server_user=artefactual \
            -D am_username=test123 \
            -D am_password=test123 \
            -D am_url=http://${ip}:${wport}/ \
            -D am_version=1.7 \
            -D am_api_key=test123 \
            -D ss_username=test123 \
            -D ss_password=test123 \
            -D ss_url=http://${ip}:${sport}/ \
            -D ss_api_key=test123 \
            -D transfer_source_path=artefactual/archivematica-sampledata/TestTransfers/acceptance-tests \
            -D home=artefactual
```

It works when I execute it on a second attempt against the same instance.

**Comment by sevein** [comment]
@jrwdunham do you have any idea why this could be happening?

**Comment by jrwdunham** [comment]
Yes, what's happening is that the new space is being created but instead of waiting for the page to refresh the `am_browser_ss_ability.py::create_ss_space` method is getting the value of the `<h1>` from the *Create Space* page. As a result, after:

        header = self.driver.find_element_by_tag_name('h1').text.strip()

the value of `header` is `'Create Space'`; and after:

        space_uuid = header.split()[0].replace('"', '').replace(':', '')

the value of `space_uuid` is `'Create'`.

I'll create a PR.
