### ISSUE TITLE
Problem: MCP batching performance gains need to be measured

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/archivematica-acceptance-tests#121]
AM18 includes a new feature that we know as MCP batching. It batches SQL queries in the MCPServer, and it also changes the engine so jobs are sent to workers in groups. This is the epic: https://github.com/artefactual/archivematica/issues/938.

**Comment by ross-spencer** [comment]
Moved to: https://github.com/archivematica/Issues/issues/386
