### ISSUE TITLE
`scp`-reliant tests with Xenial need identity-file-based auth

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#20]
With Xenial vagrant/ansible deploys, the vagrant/vagrant username/password assumption no longer holds, which breaks `scp`-reliant tests, which require password-authenticated `scp`.

The solution would seem to be:

1. add another option (and some documentation) to the acceptance tests, e.g., `-D ssh_identity_file=/path/to/.vagrant/machines/am-local/virtualbox/private_key`
2. modify `scp_server_file_to_local` of archivematicaselenium.py to use `ssh_identity_file` if present instead of the current `server_password`
3. add documentation explaining this

See https://github.com/artefactual/deploy-pub/issues/42 for more details.

**Comment by sevein** [comment]
Please, see: https://github.com/artefactual/deploy-pub/issues/42#issuecomment-326358539.
