### ISSUE TITLE
Acceptance tests on docker container.

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/archivematica-acceptance-tests#21]
Regarding [am issue #2](https://github.com/artefactual-labs/am/issues/2)

There is a need for running acceptance tests on the archivematica docker hub ( https://github.com/artefactual-labs/am ).

A new branch called acceptance-tests-docker will be created on the acceptance-test repo that includes the dockerfile and scripts.

**Comment by jrwdunham** [comment]
Fixed by https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/27
