### ISSUE TITLE
Problem: Need a feature file to describe a 'headless' archivematica

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/archivematica-acceptance-tests#23]
Columbia University Library is sponsoring development work in Archivematica to improve the performance of automated pipelines.  The first phase of this work involves removing ElasticSearch from the components that are installed with Archivematica.  

When Archivematica is run in an entirely automated configuration - with new content being ingested, processed and packaged into AIP's entirely without human intervention, using Elasticsearch does not provide any benefits.  This configuration can be referred to as 'headless', in the sense that the dashboard component is not being used as a gui, but only for the REST API to control the flow of content through the system.

Excluding Elasticsearch from the list of components installed and used by Archivematica will reduce the operational complexity and the required compute resources.   

We need a Feature File that describes the expected behaviour when installing or upgrading Archivematica, to be clear how the process should work to allow both this new mode to operate without breaking existing installations.  The Feature File will also need to describe the expected behaviour when a headless system is running.

**Comment by kellyannewithane** [comment]
Link to google doc [here](https://docs.google.com/document/d/1Wz32cWnAoODgM26dG5yV80TyX4B2giFOOf4YKDwExCE/edit#)

Columbia scalability enhancements
Phase 1 -- turn off indexing option
Phase 1 description: Archivematica uses ElasticSearch to index detailed metadata about each Transfer and AIP that is produced. For organizations that have an existing repository with its own indexing solution, this extra indexing work in ElasticSearch is redundant and ends up being both a scalability and performance bottleneck.

Phase 1 objective: When installing Archivematica, add user-controlled configuration to not install indexing.

Following are possible steps that need to be taken to either include or exclude indexing service from AM install or upgrade.
Scenario 1 Fresh installation 
1.1	At install give choice to install indexing service (Y/N)
OR
1.2	At install ES is included unless it’s excluded (command needed to disable ES)


Scenario 2 Upgrade (optional - or is 2.1 mandatory?)
2.1	Upgrade - do not have indexing service and want to continue that way
OR
2.2	Upgrade - have indexing service and want to continue that way
OR
2.3	Upgrade - have indexing service and choose to remove
OR
2.4	Upgrade - do not have indexing service and choose to add

Measurement of success
ability to run a command and see that ES has not been installed in CLI for fresh install and for upgrade (1.1 and 2.1)
no Backlog, Appraisal or Archival Storage tabs in UI
no AIP index job in Store AIP microservice in UI
at Create SIP on transfer tab, no send to backlog option
complete documentation for admin and users
