### ISSUE TITLE
Enhancement: Acceptance tests for new CCA scripts needed

### ISSUE THREAD

**Issue by joel-simpson** [artefactual-labs/archivematica-acceptance-tests#29]
We have a project for the Canadian Centre for Architecture that has two deliverables: 
- a script to create DIPs in a particular structure for CCA researchers
- a script to upload those DIPs to an instance of Atom.

Both of these scripts need acceptance tests to specify the desired functionality and supported automated testing of that functionality.

**Comment by jraddaoui** [comment]
Addressed in https://github.com/artefactual-labs/archivematica-acceptance-tests/commit/ed426ecac7f9596e50c34ac5ffa2802f6aea2af7
