### ISSUE TITLE
Enhancement: create feature file comparing performance with/without stdout/err in db

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#32]
Create a feature file that describes anticipated behaviour when the same transfer is run through two different Archivematica deployments which are identical except that one has client scripts that pass stdout/stderr back to MCPServer to be stored in the database and the other simply discards such stdout/stderr. The feature file should express an expectation that the stdout/stderr-discarding system should have significant relative performance gains.

**Comment by jrwdunham** [comment]
See https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/37

**Comment by kellyannewithane** [comment]
https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/dev/issue-11444-performance-stdout-no-write/features/core/performance-stdout-no-write.feature

**Comment by jrwdunham** [comment]
See PR https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/47.
