### ISSUE TITLE
Problem: Expand feature file for Issue #23 to include improving user interface

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual-labs/archivematica-acceptance-tests#33]
After disabling elasticsearch at fresh install, improve the user interface so that it's clear in AM dashboard that indexing is turned off.

**Comment by kellyannewithane** [comment]
https://github.com/artefactual-labs/archivematica-acceptance-tests/issues/33

**Comment by jrwdunham** [comment]
Closed by https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/50
