### ISSUE TITLE
Problem: need to create automated method of disabling elasticsearch

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual-labs/archivematica-acceptance-tests#34]
Current [feature file](https://github.com/artefactual-labs/archivematica-acceptance-tests/commit/994ad785b5e920a86bb22a267700dbdd8eac71a4) only includes manual method of disabling elasticsearch.  Need to also automate this process.

**Comment by kellyannewithane** [comment]
Feature file describes docker compose which is an automated method

**Comment by jrwdunham** [comment]
@sromkey I believe this can be considered Done because https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/master/features/core/indexless.feature describes how to deploy indexless-ly in an automated way via Docker Compose (as per Kelly's comment above).
