### ISSUE TITLE
Problem: tests do not specify the type of Archivematica installation that they are expected to pass on

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#45]
This could be specified in a JSON/YAML file:

    {
        "installations": [
            {
                "archivematica": "99922b55bf3c741d409957cb04f520cf989868a6",
                "archivematica-storage-service": "4ad0f042039810849e3f12047a1fc12cdb3b78c4",
                "archivematica-sampledata": "ab40cbfe9b17d0f2e23369f4ff176d149c0a7fcd"
            },
            {
                "archivematica": "qa/1.x",
                "archivematica-storage-service": "qa/0.x",
                "archivematica-sampledata": "master"
            }
    }

**Comment by ross-spencer** [comment]
Closing as * i think * this will be covered with https://github.com/archivematica/Issues/issues/778
Partial resolution in this PR: https://github.com/archivematica/Issues/pull/849

We do still anticipate questions around this topic, i.e. what do do now for index-less installs? What do we do for an installation with output logging turned off? *"How do we test Archivematica permutations?"*
