### ISSUE TITLE
Problem: need a basic feature for AM sanity checking

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#49]
If only one feature can be run in CI/CD system, this should be the one. It should do and test the following:

- Create an AIP from a transfer source (using processing configuration or making decisions?)
  - normalize for preservation
- Verify that at least some MS outputs are as expected, e.g., by clicking on the gear icon of file identification and verifying 0 exit codes and substrings in stdout
- Wait for AIP to be created and inspect it and make assertions about it:
  - METS file is XSD-valid and Schematron-valid
  - preservation derivatives exist on disk
  - METS file has crucial state correct (PREMIS events, relationships, ...)
  - ...
- Attempt a re-ingest? (Breaking re-ingest seems a common consequence of new AM dev work...)

**Comment by jraddaoui** [comment]
Can we create that AIP with a fixed UUID? We're about to add a test that requires an AIP and we could probably make it pass if we have one with a fixed UUID.

**Comment by ross-spencer** [comment]
Closing as this is anticipated to be covered by the range of black-box tests created as part of the initiative with @wellcometrust. 

The tag for these tests is `@black-box`. There are a range of PRs associated with that work [here](https://github.com/artefactual-labs/archivematica-acceptance-tests/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+black-box).
