### ISSUE TITLE
Problem: adding new feature files creates clutter

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/archivematica-acceptance-tests#5]
The feature files in this repo are not currently organized into namespaces or folders.  It is hard to tell which features are 'core' Archivematica features and which are related to new development work.

**Comment by jrwdunham** [comment]
Fixed by c8018e90133bd2e36c13df518c88e7e2c2f938a2. Core features are in features/core/ and development features are in features/dev/
