### ISSUE TITLE
Can AIPs be reviewed without indexing?

### ISSUE THREAD

**Issue by barmintor** [artefactual-labs/archivematica-acceptance-tests#51]
in Columbia/indexless.feature
 there is an ambiguity about whether review is possible without the `Index (transfer)` service - the decision point suggests it is, but the mechanics are not clear to us. Can the scenario be clarified as to whether review is actually possible?

**Comment by jrwdunham** [comment]
Yes, an AIP can be reviewed with ES indexing disabled. While the Archival Storage tab is disabled in that case, it is still possible to query AM's HTTP API to get the status of an AIP. If the status is complete, then the AIP can be retrieved from the Storage Service's API or GUI.

To reflect this, the wording of the relevant step has been changed to `When the user queries the API until the AIP has been stored`. See https://github.com/artefactual-labs/archivematica-acceptance-tests/blob/master/features/Columbia/indexless.feature#L49.

See the [Automation Tools](https://github.com/artefactual/automation-tools/blob/master/transfers/transfer.py#L137 for an example of querying AM's API to get the status of an AIP.

**Comment by kellyannewithane** [comment]
@barmintor can we close this issue?

**Comment by barmintor** [comment]
@dvsokolova is this answer satisfactory?
