### ISSUE TITLE
Package should be reflected in the scenario methods for deployment

### ISSUE THREAD

**Issue by barmintor** [artefactual-labs/archivematica-acceptance-tests#52]
in Columbia/indexless.feature
 `manual` and `ansible` are in the WIP document. It's not clear to us whether `manual` is intended to mean "via package, e.g. rpm". If not, `package` should be added to the scenario's methods.

**Comment by barmintor** [comment]
it's also not clear whether the RPM deployments involve completely distinct packages for disabled indexing or if they presume a postscript will be run with configuration options.

**Comment by jhsimpson** [comment]
`manual` is intended to mean "via package, i.e., rpm or deb".  I will update the feature file to make this more explicit.

Both rpm and deb deployments should use the same packages whether or not indexing is disabled.  Index disabling is accomplished through post-install configuration (which can be automated). I will update the feature file to make this more explicit.

**Comment by jrwdunham** [comment]
I have addressed this in https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/67. See https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/67/files#diff-2111642f3b647c6b56b0cac05b9e225eR45.
