### ISSUE TITLE
Where are PRONOM identification errors signalled when stderr is not stored in database?

### ISSUE THREAD

**Issue by barmintor** [artefactual-labs/archivematica-acceptance-tests#55]
in core/performance-stdout-no-write.feature (WIP)

It's unclear how Molly would be alerted to missing PRONOM characterizations, if at all. These are frequent sources of errors in Columbia content.

**Comment by jrwdunham** [comment]
@barmintor @jhsimpson In short, a non-zero exit code in the task details for the "Identify file format" indicates that no PRONOM id was found. 

One complication is that Fido (or, rather, the AM Fido FPR command) will make incorrect identifications based on the extension, in which case it will return a 0 exit code. Even when output capture is enabled, it is not possible to determine how Archivematica's Fido identification command has come to its conclusion, i.e., whether it was via a matching of byte patterns or via file extension alone. In short, the exit code indicates whether identification was successful and it is not possible to identify false identifications even when outputs are captured.

To determine the above, I created a transfer containing an unidentifiable file (random bytes) called `unidentifiable` and a copy of that same file with the `.txt` extension. Here are the results of running that transfer through Archivematica with "id tool" and "`capture_output`" as variables.

<table>
  <thead>
    <tr>
      <th><code>capture_output</code></th>
      <th>id tool</th>
      <th>file name</th>
      <th>task exit code</th>
      <th>PRONOM id</th>
      <th>task stdout</th>
      <th>task stderr</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>False</code></td>
      <td>Siegfried</td>
      <td>unidentifiable</td>
      <td>255</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><code>False</code></td>
      <td>Siegfried</td>
      <td>unidentifiable.txt</td>
      <td>255</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><code>True</code></td>
      <td>Siegfried</td>
      <td>unidentifiable</td>
      <td>255</td>
      <td></td>
      <td></td>
      <td><pre>siegfried determined that the file format is UNKNOWN
Error: IDCommand with UUID df074736-e2f7-4102-b25d-569c099d410c exited non-zero.</pre>
      </td>
    </tr>
    <tr>
      <td><code>True</code></td>
      <td>Siegfried</td>
      <td>unidentifiable.txt</td>
      <td>255</td>
      <td></td>
      <td></td>
      <td><pre>siegfried determined that the file format is UNKNOWN
Error: IDCommand with UUID df074736-e2f7-4102-b25d-569c099d410c exited non-zero.</pre>
      </td>
    </tr>
    <tr>
      <td><code>False</code></td>
      <td>Fido</td>
      <td>unidentifiable</td>
      <td>255</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><code>False</code></td>
      <td>Fido</td>
      <td>unidentifiable.txt</td>
      <td>0</td>
      <td>x-fmt/111</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><code>True</code></td>
      <td>Fido</td>
      <td>unidentifiable</td>
      <td>255</td>
      <td></td>
      <td><pre></pre>
      <td><pre>Fido exited 0 and no format was found.
stdout: KO,148,,,,10000000,"/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/thu4-78606900-acbd-4f06-9228-ffebb5db73e3/objects/unidentifiable",,"fail"
---
stderr: FIDO v1.3.7 (formats-v92.xml, container-signature-20170920.xml, format_extensions.xml)
FIDO: Processed      1 files in 220.33 msec,  5 files/sec
Error: IDCommand with UUID 76006ad7-a401-48f6-98f6-2efc01003276 exited non-zero.</pre></td>
      </td>
    </tr>
    <tr>
      <td><code>True</code></td>
      <td>Fido</td>
      <td>unidentifiable.txt</td>
      <td>0</td>
      <td>x-fmt/111</td>
      <td><pre>IDCommand UUID: 76006ad7-a401-48f6-98f6-2efc01003276
File: (bc2bb997-805e-4b36-9d17-f8601f112aed) /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/thu4-78606900-acbd-4f06-9228-ffebb5db73e3/objects/unidentifiable.txt
x-fmt/111
Command output: x-fmt/111
/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/thu4-78606900-acbd-4f06-9228-ffebb5db73e3/objects/unidentifiable.txt identified as a Generic TXT</pre></td>
      <td><pre></pre>
      </td>
    </tr>
  </tbody>
</table>

**Comment by kellyannewithane** [comment]
@barmintor Do you have any more comments or questions to add here?
