### ISSUE TITLE
Problem: helper scripts broken

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/archivematica-acceptance-tests#6]
The commit 3777b1c7e95897f29ea0ae85570e2519345a9a2f added a change to the get_am_sel_cli() method in environment.py.  This method requires an input parameter now.  It is called from two helper scripts (close_all_transfers.py and close_all_ingest.py), those scripts don't work now.

**Comment by jrwdunham** [comment]
Fixed by 267161269786a6535c577a2de1d782e1de7b2638
