### ISSUE TITLE
Problem: transfers cannot be initiated on directories not visible in the file browser

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#63]
If a file is so far down in the transfer source file browser that it is not visible, then the Selenium logic is currently failing to click on it. Note: this may be fixed for clicking to *open* a directory but not clicking to *select* a directory.

**Comment by ross-spencer** [comment]
For the large-part we are managing this now by enabling transfers to be started using the API. The release commit which enables this for a good number of the original AMAUAT tests is here: https://github.com/artefactual-labs/archivematica-acceptance-tests/commit/662d57b3977880f9266573133275d87ffa43fdfa
