### ISSUE TITLE
Problem: AIP encryption features cannot be run against docker deploys

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#65]
This is because these features/tests require scp/ssh and docker containers don's allow that.

**Comment by ross-spencer** [comment]
I'm not clear on the precise commit that enabled this, but we were testing this functionality successfully in the recent `1.10` work. The release commit is here: https://github.com/artefactual-labs/archivematica-acceptance-tests/commit/662d57b3977880f9266573133275d87ffa43fdfa closing for now, but can be re-opened (or at least re-opened in am/issues if closed in error).
