### ISSUE TITLE
Problem: we lack confirmation that SS posix_move results in a performance improvement

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#76]
[SS PR 320](https://github.com/artefactual/archivematica-storage-service/pull/320) introduced the `posix_move` method of the `Space` class, which moves files directly from one location to another without the intermediary move to a staging path. We need a feature file that describes our expectation that this change results in a performance improvement and we need that feature file to provide an automated confirmation of that expectation.

**Comment by sevein** [comment]
FWIW I've been running some local tests here: https://github.com/JiscRDSS/archivematica-storage-service/pull/30. For a transfer with a file of 50M filled with `dd if=/dev/urandom of=file bs=1M count=50` I'm seeing that `/api/transfer/start_transfer/` takes about half: 1.36 vs 2.76 seconds.

**Comment by ross-spencer** [comment]
Closing as we are a number of releases past `1.8`/`0.12.0` now and it seems unlikely we would go back to confirm this via experiment. Performance metrics for future releases are however in the works so this will be easier to tackle moving forward.
