### ISSUE TITLE
Problem: we lack confirmation that checksum verification de-duplication results in a performance improvement

### ISSUE THREAD

**Issue by jrwdunham** [artefactual-labs/archivematica-acceptance-tests#78]
[AM PR 1012](https://github.com/artefactual/archivematica/pull/1012) aimed to increase the efficiency of checksum verification. We need a feature file that describes our expectation that this change results in a performance improvement and we need that feature file to provide an automated confirmation of that expectation.

**Comment by ross-spencer** [comment]
Closing as we are a number of releases past `1.7` now and it seems unlikely we would go back to confirm this via experiment. Performance metrics for future releases are however in the works so this will be easier to tackle moving forward.
